### PR TITLE
Get and set full state of Random Number Generator

### PR DESCRIPTION
**Pull request by jucor**
Hi Ronan, Koray, Clement

Working with Andreas, we implemented two functions `torch.getRNGState()` and `torch.setRNGState()` to manipulate the whole internal state of the Random Number Generator (RNG). This is in complement to the initial seed, for which functions already exist: the initial seed requires to re-do the whole sequence of calls to random() until the point of interest, whereas the state before the last call to random() is enough to reproduce without re-running through everything. Very useful for debugging of Monte-Carlo code!

Koray helped us a lot for moving the headers around. This was mandatory to allow our new functions in Random.c to return a Tensor. 

Note: I have manually wrapped the C function `_getRNGState()`, because I did not find how to return multiple `long` from a function using the `wrap.lua` and `returned = true`. I am actually not sure if it is possible yet: all the `long` I have seen in the codebase where `creturned=true`, not `returned=true`. I will be happy to discuss a patch about it, but that's a separate issue from the RNG state.

Please let me know if I can be of any help getting this accepted!
Cheers,

Julien

### CODE REVIEW

**Comment by jucor** [comment]
PS: as you will see, I've put a minimal unit test example to clarify the behaviour. Will update the dok tomorrow, too.

**Comment by jucor** [comment]
Documentation: check.

**Comment by clementfarabet** [comment]
It looks good to me; but I'll let Ronan go over this, I know he has some pretty tight rules on randomness & seeds :-)

**Comment by jucor** [comment]
Thanks Clement. Looking forward to Ronan's comments! Curious to see what are tight rules on randomness :-)

**Comment by jucor** [comment]
Solved by 614ac15fc1bc71a89004de2dadc4cb8c3cce6ba2

**Pull request closed without merging**
