### PR TITLE
Fixed PairwiseDistance for odd Lp norms

### PR DESCRIPTION
**Pull request by jonathantompson**
Just added abs() call when norm is odd.

### CODE REVIEW

**Comment by soumith** [comment]
this is incorrect. your gradients will be screwed up. you need to use an nn.abs module instead so that the gradients are propagated correctly.

**Comment by jonathantompson** [comment]
I admire your enthusiasm...  But I don't know if I believe you :-)  

Can you please explain what you mean in more detail?

Or alternatively show me an example that breaks.

For non-batch the forward prop uses the dist() function... which has an fabsf.  I've replicated that in updateOutput.

**Comment by soumith** [comment]
sorry i must've said "this looks incorrect". 

In your pull request, you do an abs, so that was my first reaction.
It looks like lines 48-50 were already added before to take care of the sign at norm=1

**Comment by clementfarabet** [comment]
Guys, to avoid any ambiguities, could we have a test added to [test](https://github.com/torch/torch7-distro/blob/master/extra/nn/test/test.lua).

I shouldn't have merged this at all without requiring a test there...

**Comment by jonathantompson** [comment]
Good point.  I'll try and get around to it tomorrow.

**Comment by jonathantompson** [comment]
So testJacobian seems straight forward...  I'll add a test for PairwiseDistance under batch and non-batch inputs.

But a few quick questions: 

A. What is the "official" torch policy for writing tests for cuda modules? I see that there are these scripts:

./extra/cuda/pkg/cutorch/test/test.lua
./extra/cuda/pkg/cunn/test/test.lua

However there isn't a test for all modules (a PairwiseDistance test doesn't exist for instance).  Is there even supposed to be?  Or do you write cuda tests only for methods that have explicit cuda implementations (i.e., they don't just use basic tensor operations like PairwiseDistance).  

B. Alternatively, do the methods in:

extra/nn/test/test.lua

ever get run using cuda tensors, rather than floats or doubles?  

C. Last question... are there memory leak tests?

**Comment by clementfarabet** [comment]
Hey Jon,

there's never been a real policy... we wrote tests for most commonly used
modules, and then grew the test base from there.

**Pull request closed without merging**
