### PR TITLE
I needed a way to do a derivative check on a Sequential...

### PR DESCRIPTION
**Pull request by abeschneider**
In order to write the derivativeCheck I needed to provide a method to get all the parameters from a Sequential, so I added getParameters(). This essentially just calls getParameters() on the modules and concatenate them. Additionally, Sequential:fromParameters() was needed, which subsequently requires Modules:fromParameters().

Unfortunately, I couldn't see a good way to write a generic fromParameters() function, since a Module has no listing of its parameters. Thus, I wrote one just for Linear with the idea that it could be implemented for other modules. However, if Modules kept a list of their parameters, this could be moved into Module.

The function Sequential:derivativeCheck(input, output, criterion, epsilon) perturbs each parameter +/- epsilon to calculate the derivative and match against the computed gradient. I've added a method to the unit test that creates an auto encoder to test out the function.

### CODE REVIEW

**Comment by koraykv** [comment]
Hi Abe,

I am not sure all this is required.

There is already jacobian checking implemented in extra/nn/Jacobian.lua
We actually test all the modules for accurate jacobians. you can find implementations of all these test at extra/nn/test/test.lua

For sequential, I don't think you need an additional function to check its derivatives. You can use the already provided functionality and check the derivatives of each layer one by one. You can find examples of this again in the test.lua file.

**Comment by abeschneider** [comment]
I actually didn't realize that there was equivalent code in the Jacobian module (I checked, but obviously not closely enough). When I submitted the code, I actually wasn't sure it would be useful to anyone else, but thought I might as submit it just in case. In either case, It looks like I still need the  version I have.

Out of curiosity, what is 'getParameters' used for? I did a grep for it, and it doesn't get used anywhere else. Does it make sense to keep the 'fromParameters' counterpart?

It looks like I still need the version I have, so it works out fine.
You can

**Comment by koraykv** [comment]
getParameters gives you a 1D vector view of all the parameters in any network architecture.

I am closing this request since it is already implemented in Torch7.

**Comment by abeschneider** [comment]
Hi Koray -- that makes sense.

I understand what getParameters() does, but I was asking (not in the clearest manner) if it makes sense to have a symmetrical function to getParameters() that turns a 1D vector into a module (which is what fromParameters does).

I don't see getParameters currently being used, so I assume it's there as a convenience function. If so, it would make sense to me to provide its counterpart.

**Pull request closed without merging**
