### PR TITLE
Added ssh support for downloading package listing.

### PR DESCRIPTION
**Pull request by rosejn**
- if an ssh:// prefixed URL is added with torch-pkg add, then it will
  use scp to copy the file from the server.

### CODE REVIEW

**Comment by clementfarabet** [comment]
Ok that's cool, I was almost about to merge it, but I'm just thinking that it might a but too simple:
one could have a GIT repo served through SSH, in which case the current torch-pkg clones the repo through ssh (I believe this works already). So maybe we should differentiate the addresses like this:

• https://url/  =  git repo, via https
• ssh://url/  =  git repo, via ssh
• servername:path/to/dir  =  straight directory (no repo), use scp

Alternately, we could have an option flag for torch-pkg, to specify the package format (git, tar, zip, ...), but that makes things a bit more heavy?

What do you think?

**Comment by rosejn** [comment]
Good point, it's better to keep consistent URLs.  Although this is only for the package listing, which currently only supports using wget or curl over http, it makes sense to leave ssh:// as meaning git over ssh.  For some reason I was thinking scp:// isn't a valid URL, but upon searching I find that it's perfectly valid, so how about using that for copying the package listing?

**Comment by clementfarabet** [comment]
Oh yes, I didn't realize it was just for the package listing!. But you're right, even in this case, it's still better to use scp:// it makes it very clear.

**Comment by rosejn** [comment]
Oh, cool, I didn't realize if I add a commit it automatically adds to the pull request.  Now just using scp://.

**Pull request merged**
