### PR TITLE
Added minibatch support to MarginRankingCriterion and PairwiseDistance.

### PR DESCRIPTION
**Pull request by vladmnih**

### CODE REVIEW

**Comment by jonathantompson** [comment]
Very nice.  I also had a version or something like this in my own fork but it's great to see this integrated into the main branch.

**Comment by clementfarabet** [comment]
Funny we were just discussing these yesterday... thanks!

**Comment by koraykv** [comment]
I think this might be a little buggy, it might just process even stochastic inputs as batch and produce batch outputs.

**Comment by clementfarabet** [comment]
Arg, really? Should I un-merge it?

On Wed, Oct 16, 2013 at 2:01 PM, koray kavukcuoglu <notifications@github.com

**Comment by koraykv** [comment]
I can fix it tonight, but now I am in the road.

**Comment by clementfarabet** [comment]
OK thanks!

On Wed, Oct 16, 2013 at 2:10 PM, koray kavukcuoglu <notifications@github.com

**Comment by rgoroshin** [comment]
I'm having problems with PairwiseDistance() backward in this update.

**Comment by koraykv** [comment]
Please try again, I just updated the code now.

**Comment by koraykv** [comment]
Sorry, I did not update the Pairwise distance, I did the margin ranking, will do that now.

**Comment by rgoroshin** [comment]
Sweet. Thanks.

On Wed, Oct 16, 2013 at 6:31 PM, koray kavukcuoglu <notifications@github.com

**Comment by koraykv** [comment]
should be fine now, please check.

**Comment by clementfarabet** [comment]
Thanks Koray, it seems to be fixed (only tried the stochastic version
though).

I guess we should really have a proper testing interface (travis?) to merge
things more safely...

On Wed, Oct 16, 2013 at 6:51 PM, koray kavukcuoglu <notifications@github.com

**Comment by koraykv** [comment]
Hehe :) I think travis together with versioned rocks would solve many problems. This way, no one would be able to use a head with test errors. We would need to create new rockspecs time to time, that is all.

**Comment by clementfarabet** [comment]
Yeah I tried to put versioned rocks in place, like in optim, but it seems
to be causing more annoyement for people...

On Wed, Oct 16, 2013 at 6:59 PM, koray kavukcuoglu <notifications@github.com

**Comment by koraykv** [comment]
yeah, stability is boring :) 
We can use a separate branch in rockspecs that we merge by hand into master ...
Or, even without versioning travis would be nice. At least we would have an indication if something went wrong...

**Comment by clementfarabet** [comment]
Yeah I vote for travis!

On Wed, Oct 16, 2013 at 7:11 PM, koray kavukcuoglu <notifications@github.com

**Pull request merged**
