### PR TITLE
openmp for add/mul/div is restricted to only large arrays (arbitrary thr...

### PR DESCRIPTION
**Pull request by soumith**
...eshold set to 100k). Also fixes some c89 commenting for the new quick sort algorithms

### CODE REVIEW

**Comment by soumith** [comment]
https://github.com/torch/image/issues/7

**Comment by soumith** [comment]
Also fixes compilation issues stemming from https://github.com/torch/torch7-distro/pull/176 .

**Comment by soumith** [comment]
tested it out. the overhead issues for small arrays is gone.

**Comment by soumith** [comment]
all unit tests seem to pass.

**Comment by clementfarabet** [comment]
OK it makes sense, thanks!

**Comment by Maratyszcza** [comment]
A safer heuristic would be "when the size of the array exceeds LLC". Multi-threading never hurts when streaming from/to memory.

**Pull request merged**
