### PR TITLE
Fixed PairwiseDifference for norms other than 1

### PR DESCRIPTION
**Pull request by jonathantompson**
OK, it turns out that the inputGrad was wrong before the batch support was added for norms other than 1...  The sign of the gradient was OK, but the magnitude was wrong.  I've fixed this but it REALLY needs review.  

Can you check that I'm using the expand function correctly (I don't think it allocates memory, but I'm not 100% sure)?

I also created "reasonably" comprehensive test for PairwiseDistance in /extra/nn/test/test.lua.  This also needs review.  The tests for fprop and bprop pass.

### CODE REVIEW

**Comment by jonathantompson** [comment]
There are still stability issues (ie divide by zero problems), that the added test didn't catch.  I want to continue testing and then I'll submit another pull request.  Sorry for the confusion.

**Comment by clementfarabet** [comment]
Hey Jon,

so I'm a bit confused by all the pull requests / issues. There's no more open pull request right? Should I wait for you to submit a new one?

If I understood correctly, PairwiseDistance is only working with L1 and batchsize=1 ?

**Comment by jonathantompson** [comment]
Correct.  I found another bug (introduced by my new code), where I forgot to check for divide by zero.

I'll push the final version soon and reopen the pull request.  Sorry for the confusion.

Yes, PairwiseDistance only works for L1.  The forward prop error is due to the recent changes to support batches.  However, looking through the git log it seems that the bprop has always been broken.  The sign of the gradient is at least correct, but the magnitude is wrong.

**Comment by clementfarabet** [comment]
Ok thanks a lot for looking into this.

I've only ever used it with L1, and no batch...

One comment on batch vs single sample: I think we should always write the
code for batch, and if the input is a single sample, reshape it into 1xN,
process it through the batch code, then reshape it back to N. This would be
good to avoid code replication.

**Comment by jonathantompson** [comment]
That's not a bad idea.  OK, I'll implement that and then push the changes once I've finished verifying it.

**Comment by clementfarabet** [comment]
Awesome, thanks!

**Comment by jonathantompson** [comment]
I think PairwiseDistance still needs a visual-inspection code review (to make sure I'm not being crazy).

It has also been tested under cuda in a working project, so I think the implementation is correct now.

**Comment by jonathantompson** [comment]
Ross and I have been using the new version of the PairwiseDistance module for a few weeks now and we haven't had any issues.  The change is API compatible and even fixes a few bugs that have existed for a very long time (the last commit today for instance).

It passes the test that I wrote for it and it works in cuda.  Is there something else I should include or test sot that the pull request is merged?

**Comment by clementfarabet** [comment]
OK let's give it a try!

**Comment by jonathantompson** [comment]
Clement, you're going to hate me.  I'm SO sorry that I have to do this, but I'm going to have to upload another pull request to fix something that I broke this morning.  I'm so sorry.

As pointed out by Ross, the Module:type() method returns self.  The PairwiseDistance:type() overload does not return self.  This means:

net = nn.PairwiseDistance(2):cuda()

will give a nil value for net.  I don't use the type conversion methods in this way, so I didn't think to check it.

I will upload a new pull request in the next 5 minutes to fix it.

**Comment by soumith** [comment]
haters gonna hate

http://www.meganhelstone.com/wp-content/uploads/2012/04/img-haters-gonna-hate-panda-352.jpeg

**Comment by clementfarabet** [comment]
I merged the other one, no problem...

**Pull request merged**
