### PR TITLE
Improved Module:getParameters() speed when using many storages

### PR DESCRIPTION
**Pull request by fidlej**
I used torch.pointer(storage) as the key when searching for a storage.
The local table storages now stores the following entries:

```
 storages[torch.pointer(storage)] = {storage, storageOffet}
```

### CODE REVIEW

**Comment by clementfarabet** [comment]
Hi Ivo, cool, we hadn't thought of using the pointer as a hash :-). Is it safe for me to merge with not testing?

**Comment by fidlej** [comment]
The code works for me. Do you suggest to add some unit tests?

**Comment by clementfarabet** [comment]
I actually forgot, but we have a full set of tests, for this function in particular, in extra/nn/test/test.lua . Did you run these? It validates that getParameters() works under most common scenarios.

Thanks!
Clément

**Comment by fidlej** [comment]
I have run the tests now. "Completed 346 asserts in 50 tests with 0 errors".
Everything was fine. Thanks for mentioning the tests.

**Comment by fidlej** [comment]
I see that hessian.lua has a custom copy of nn.Module.getParameters().
I should keep the copy synchronized. I will update it tomorrow.

**Comment by clementfarabet** [comment]
Awesome, thanks for running the tests!

**Pull request merged**
